# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9dc49a8120c9391a2c2e5a7910ca8d67d0d790cfe2bf411b9bec2230df823d71bd92a5ad9a9ff0b74a03869b46a1ec208e91120fbd34ed16d10044db3a7a394c

test:
  secret_key_base: 8c321d4755bfb8f27755c76b3f8d052aaaa6df0314f2c2ba8cd0e5931fea972f0c996925ba76d54c0a2056e6d182bc58a2d7cf88a72bf6de525e175924560165

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
